title = "IE3142 DevSecOps Gitleaks Configuration"

[extend]
useDefault = true

[allowlist]
description = "Allow intentionally embedded OWASP Juice Shop test/vulnerability fixtures"

paths = [
  '''application/juice-shop/test/.*''',
  '''application/juice-shop/data/static/users\.yml''',
  '''application/juice-shop/lib/insecurity\.ts''',
  '''application/juice-shop/routes/login\.ts''',
  '''application/juice-shop/terraform/networking\.tf''',
  '''application/juice-shop/infrastructure/terraform/networking\.tf'''
]
